#!/usr/bin/env python3
"""
report.py — Generate an intelligence report for the active task.
Pulls from real episodic logs + graduated lessons.
"""
import json
import os
import datetime
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _agent_utils import find_project_root, agent_dir

ROOT  = find_project_root()
AGENT = agent_dir(ROOT)


def generate_report() -> str:
    active_file = AGENT / ".active_task"
    if not active_file.exists():
        return "❌ No active task. Run `/task <id>` first."

    task_id = active_file.read_text().strip()
    print(f"📋 Generating UALL Report for Task: {task_id}...")

    # Gather logs for this task
    task_logs = []
    episodic_dir = AGENT / "memory" / "episodic"
    for log_file in sorted(episodic_dir.glob("*.jsonl")):
        with open(log_file) as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    data = json.loads(line)
                    if data.get("task_id") == task_id:
                        task_logs.append(data)
                except json.JSONDecodeError:
                    continue

    # Collect anomalies
    anomalies = {}
    for log in task_logs:
        for a in log.get("anomalies", []):
            anomalies[a] = anomalies.get(a, 0) + 1

    failures = [l for l in task_logs if l.get("status") == "Failed"]

    # Gather graduated lessons (real data)
    graduated_lessons = []
    lessons_file = AGENT / "memory" / "graduated" / "LESSONS.jsonl"
    if lessons_file.exists():
        with open(lessons_file) as f:
            for line in f:
                try:
                    lesson = json.loads(line)
                    graduated_lessons.append(
                        f"- **{lesson.get('id', 'N/A')}**: {lesson.get('title', lesson.get('source_file', 'Unnamed'))}"
                    )
                except json.JSONDecodeError:
                    pass

    report_lines = [
        f"## 🤖 UALL Intelligence Report: {task_id}",
        f"**Generated**: {datetime.datetime.now().isoformat()[:19]}",
        "",
        "### 🔍 Observations",
        f"- **Atomic Actions Logged**: {len(task_logs)}",
        f"- **Failures**: {len(failures)}",
        f"- **Anomaly Types**: {len(anomalies)}",
    ]

    if anomalies:
        report_lines.append("\n### ⚠️ Anomalies Detected")
        for a, count in sorted(anomalies.items(), key=lambda x: -x[1]):
            report_lines.append(f"- {a} (×{count})")

    if failures:
        report_lines.append("\n### ❌ Failed Commands")
        for f in failures[-5:]:  # Last 5 failures
            report_lines.append(f"- `{f.get('command', 'unknown')[:80]}` — {f.get('anomalies', [])}")

    report_lines.append("\n### 💡 Institutional Knowledge")
    if graduated_lessons:
        report_lines.append("Graduated lessons in the Playbook:")
        report_lines.extend(graduated_lessons[-5:])  # Show last 5
    else:
        report_lines.append("No graduated lessons yet. Run `/dream` then `/graduate`.")

    report_lines += [
        "",
        "---",
        "*Auto-generated by UALL Kernel. Run `/graduate` to persist new learnings.*",
    ]

    return "\n".join(report_lines)


if __name__ == "__main__":
    print(generate_report())
